# Generated by Django 5.0 on 2023-12-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DMA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("network_repr", models.JSONField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="dma",
            constraint=models.UniqueConstraint(fields=("id", "code"), name="id_code"),
        ),
    ]
