# Generated by Django 5.0 on 2024-07-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeFlow',
            fields=[
                ('pipe_main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pipe_main_flows', serialize=False, to='assets.pipemain')),
                ('flow_data', models.JSONField()),
            ],
        ),
    ]
