# Generated by Django 5.0 on 2024-07-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_data', models.JSONField()),
                ('pipe_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='assets.pipemain')),
            ],
        ),
    ]
