# Generated by Django 5.0 on 2024-07-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('waterpipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeflow',
            name='id',
        ),
        migrations.AlterField(
            model_name='pipeflow',
            name='pipe_main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pipe_main_flows', serialize=False, to='assets.pipemain'),
        ),
    ]
