# Generated by Django 5.0 on 2024-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterpipes', '0002_alter_pipeflow_flow_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeflow',
            name='flow_data',
            field=models.JSONField(decoder=dict, encoder=dict),
        ),
    ]
