
ANODES_LAYER_INDEX=0
BOREHOLES_LAYER_INDEX=1
BULK_METERS_LAYER_INDEX=2
DISCHARGE_LAYER_INDEX=3
FLOATVALVES_LAYER_INDEX=4
HYDRANTS_LAYER_INDEX=5
INSERTIONFLOWMETER_LAYER_INDEX=6
LISTENINGPOST_LAYER_INDEX=7
MARKERPOST_LAYER_INDEX=8
MOTIVEWATERPOINT_LAYER_INDEX=9
NONRETURNVALVE_LAYER_INDEX=10
OPENPIPE_LAYER_INDEX=11
POTABLE_WATER_STORAGE_LAYER_INDEX=12
PRESSURETAPPINGS_LAYER_INDEX=13
QUALITYSAMPLINGPOINT_LAYER_INDEX=14
RAWWATERSTORAGE_LAYER_INDEX=15
REGULATORS_LAYER_INDEX=16
REVENUEMETERS_LAYER_INDEX=17
STOPTAP_LAYER_INDEX=18
STRAINER_LAYER_INDEX=19
WATERAIRVALVE_LAYER_INDEX=20
WATERCHEMICALINJECTIONPOINTS_LAYER_INDEX=21
WATERFACILITYCONNECTIONS_LAYER_INDEX=22
WATERHATCHBOX_LAYER_INDEX=23
WATERINTAKE_LAYER_INDEX=24
WATER_ISOLATION_VALVES_LAYER_INDEX=25
WATERPIPECONNECTIONS_LAYER_INDEX=26
WATER_PUMPING_FACILITIES_LAYER_INDEX=27
WATER_TREATMENT_WORKS_LAYER_INDEX=28
WELL_LAYER_INDEX=29
DMA_LAYER_INDEX=30
PIPES_LAYER_INDEX=31


OPTSTRING=":f:"

while getopts ${OPTSTRING} opt; do
    case ${opt} in
        f)
            python3 manage.py layer_stw_dmas_to_sql -f ${OPTARG} -x ${DMA_LAYER_INDEX}
            python3 manage.py layer_stw_mains_to_sql -f ${OPTARG} -x ${PIPES_LAYER_INDEX}
            python3 manage.py layer_stw_hydrants_to_sql -f ${OPTARG} -x ${HYDRANTS_LAYER_INDEX}
            python3 manage.py layer_stw_listening_posts_to_sql -f ${OPTARG} -x ${LISTENINGPOST_LAYER_INDEX}
            python3 manage.py layer_stw_isolation_valves_to_sql -f ${OPTARG} -x ${WATER_ISOLATION_VALVES_LAYER_INDEX}
            python3 manage.py layer_stw_bulk_meters_to_sql -f ${OPTARG} -x ${BULK_METERS_LAYER_INDEX}
    esac
done
