# Generated by Django 5.0 on 2023-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_y", models.FloatField(max_length=50)),
                ("shape_x", models.FloatField(max_length=50)),
            ],
        ),
    ]
