# Generated by Django 5.0 on 2023-12-22 08:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_length", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_main_dma",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hydrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hydrant_dma",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logger_dma_1",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_meter_dma_1",
                        to="utilities.dma",
                    ),
                ),
                (
                    "dma_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_meter_dma_2",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrunkMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField()),
                ("shape_length", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trunk_dma",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
    ]
