version: "3"

services:
  cwageodjangodev:
    container_name: udtcwageodjangodev
    image: cwa_geodjango_dev
    build:
      context: ./
      dockerfile: Dockerfile_cwa_geodjango_dev
    links:
      - udtpostgis
      - udtneo4j
    volumes:
      - ../../cwa/cwa_geodjango:/opt/udt/cwa/cwa_geodjango/
      - ../../cwm:/opt/udt/cwm/
      - ../../data:/opt/udt/data/
    restart: always
