version: "3"

#name: <your project name>

services:
  udtpostgis:
    container_name: udtpostgis
    platform: linux/amd64
    ports:
      - 5432:5432
    env_file:
      - ./env_files/.db_env
    image: postgis/postgis
    restart: always
    # Adjust params in db-init-config.sh before running this compose
    volumes:
      - ../scripts/postgis/db-init-config.sh:/docker-entrypoint-initdb.d/db-init-config.sh