version: "3"

services: 
  apidrf: 
    container_name: udtapidrf
    image: api_drf
    build: 
      context: ./
      dockerfile: Dockerfile_api_drf
    links: 
      - udtpostgis
      - udtcwageodjangodev
    volumes: 
      - ../../api/api_drf:/opt/udt/api/api_drf/
      - ../../cwa/cwa_geodjango:/opt/udt/cwa/cwa_geodjango/
      - ../../cwm:/opt/udt/cwm/
    restart: always
