# -*- coding: utf-8 -*-
"""MultiLineString to LineString.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTY3Unqth7Gy_d5IcXTUxxIXI4rF7YNa
"""

import fiona
import shapely
from shapely import wkt
from shapely.geometry import Point, MultiPoint, LineString, MultiLineString
import os
import geopandas as gpd
import pandas as pd
from google.colab import drive

drive.mount('/content/drive/', force_remount=True)

os.chdir("/content/drive/MyDrive")

original_gpkg = "/content/drive/MyDrive/tw_cleanwater_network_layers_singlepart_subtypes_loggerstatus.gpkg"

new_gpkg = '/content/drive/MyDrive/tw_cleanwater_network_layers_20240412.gpkg'

for layer_name in fiona.listlayers(original_gpkg):
    # make gdf from layer
    original_gdf = gpd.read_file(original_gpkg, layer=layer_name)
    geometry_type = wkt.loads(original_gdf['wkt_geom_4326'][0]).geom_type
    print(geometry_type)
    if geometry_type == 'MultiLineString':
        original_gdf['wkt_geom_4326'] = wkt.dumps(original_gdf.geometry.to_crs('EPSG:4326'))
        # save out layer to new gpkg
        original_gdf.to_file(new_gpkg, driver="GPKG", layer=layer_name)
    else:
        original_gdf.to_file(new_gpkg, driver="GPKG", layer=layer_name)

for layer_name in fiona.listlayers(old_gpkg):
    old_gdf = gpd.read_file(old_gpkg, layer=layer_name)
    if old_gdf.geom_type != 'Point':
      print(layer_name, old_gdf.shape)

for layer_name in fiona.listlayers(new_gpkg):
    new_gdf = gpd.read_file(new_gpkg, layer=layer_name)
    if new_gdf.geom_type != 'Point':
      print(layer_name, new_gdf.shape)

for layer_name in fiona.listlayers(new_gpkg):
    new_gdf = gpd.read_file(new_gpkg, layer=layer_name)
    if (new_gdf.geom_type != 'Point').any():
      print(new_gdf.head(1))