# Generated by Django 5.0 on 2024-01-22 06:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_length", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=27700
                    ),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_distribution_mains",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hydrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_hydrants",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_loggers",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_1_network_meters",
                        to="utilities.dma",
                    ),
                ),
                (
                    "dma_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_2_network_meters",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkOptValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_1_network_opt_valves",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PressureControlValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_1_pressure_control_valves",
                        to="utilities.dma",
                    ),
                ),
                (
                    "dma_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_2_pressure_control_valves",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrunkMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_length", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=27700
                    ),
                ),
                (
                    "dma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_trunk_mains",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
    ]
