# Generated by Django 5.0 on 2024-01-08 11:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkOptValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                ("shape_x", models.FloatField()),
                ("shape_y", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_1_network_opt_valves",
                        to="utilities.dma",
                    ),
                ),
                (
                    "dma_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dma_2_network_opt_valves",
                        to="utilities.dma",
                    ),
                ),
            ],
        ),
    ]
