# Generated by Django 5.0 on 2024-07-28 06:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_boreholes', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BulkMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_bulk_meters', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_chambers', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_connection_meters', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_consumption_meters', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Hydrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('acoustic_logger', models.BooleanField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_hydrants', to='utilities.dma')),
            ],
        ),
        migrations.CreateModel(
            name='IsolationValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_isolation_valves', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_loggers', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NetworkMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('subtype', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_network_meters', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NetworkOptValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('acoustic_logger', models.BooleanField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_network_opt_valves', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NonReturnValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_nonreturn_valves', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OperationalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('subtype', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_operational_sites', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PipeMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('material', models.CharField(db_index=True, max_length=255)),
                ('pipe_type', models.CharField(db_index=True, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diameter', models.FloatField()),
                ('dmas', models.ManyToManyField(related_name='dma_pipe_mains', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PotableWaterStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_potable_water_storages', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PressureControlValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('subtype', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_pressure_control_valves', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PressureFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('subtype', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_pressure_fittings', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_regulators', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RevenueMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_revenue_meters', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WaterFacilityConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_water_facility_connections', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WaterPipeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_water_pipe_connections', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WaterPumpingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_water_pumping_facilities', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WaterTreatmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('geometry_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sub_type', models.CharField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dmas', models.ManyToManyField(related_name='dma_water_treatment_works', to='utilities.dma')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
