const QUERY_PREFIX = 'cw_gis_assets'
export const DIST_MAINS = `${QUERY_PREFIX}/distribution_main`
export const TRUNK_MAINS = `${QUERY_PREFIX}/trunk_main`
export const CHAMBER = `${QUERY_PREFIX}/chamber`
export const HYDRANT = `${QUERY_PREFIX}/hydrant`
export const LOGGER = `${QUERY_PREFIX}/logger`
export const NETWORK_METER = `${QUERY_PREFIX}/network_meter`
export const NETWORK_OPT_VALVE = `${QUERY_PREFIX}/network_opt_valve`
export const OPERATIONAL_SITE = `${QUERY_PREFIX}/operational_site`
export const PRESSURE_CONTROL_VALVE = `${QUERY_PREFIX}/pressure_control_valve`
export const PRESSURE_FITTING = `${QUERY_PREFIX}/pressure_fitting`