FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN DEBIAN_FRONTEND=noninteractive apt update

RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y \
        vim \
        python3 \
        python3-dev \
        python3-pip \
        gunicorn

RUN mkdir -p /opt/sotware/udt2/

WORKDIR /opt/sotware/udt2/

COPY ./udt/sotware/udt2 .

RUN pip3 install -r requirements.txt

EXPOSE 8000

#CMD ["gunicorn", "config.wsgi", "-b 0.0.0.0:8000", "--workers=6"]

CMD ["python", "manage.py", "runserver" "0.8000"]
