# Generated by Django 5.0 on 2024-02-26 10:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_chambers", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=27700
                    ),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_distribution_mains", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hydrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_hydrants", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_loggers", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_network_meters", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkOptValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_network_opt_valves", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_operational_sites", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PressureControlValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_pressure_control_valves", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PressureFitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(srid=27700),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_pressure_fittings", to="utilities.dma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrunkMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gisid", models.IntegerField(unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=27700
                    ),
                ),
                (
                    "dma",
                    models.ManyToManyField(
                        related_name="dma_trunk_mains", to="utilities.dma"
                    ),
                ),
            ],
        ),
    ]
